<?php
$host = DATABASE_HOST_NAME;
$user = DATABASE_USER_NAME;
$pass = DATABASE_PASSWORD;
$dbname = DATABASE_NAME;
$myusername = AFRICASTALKING_USERNAME;
$myapikey = AFRICASTALKING_API_KEY;
$short_code = AFRICASTALKING_USER_SHORT_CODE;